title : Bioinformatics Wiki
author: BISB/BMI students at UC San Diego

# Short description about the book
description: >-
  A collection of bioinformatics and computational biology best practices.

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/bioinfo-ucsd/wiki
  path_to_book                : "wiki"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
# Uncomment when adding references
# bibtex_bibfiles:
#    - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image
